services:
  mediawiki:
    build:
      context: .docker/mediawiki
      args:
        MEDIAWIKI_VERSION: ${MEDIAWIKI_VERSION:-1.41.0}
    # image: mediawiki:${MEDIAWIKI_VERSION:-1.41.0}
    restart: unless-stopped
    ports:
      - 80:80
    environment:
      HOST_UID: ${HOST_UID:-1000}
      HOST_GID: ${HOST_GID:-1000}
      XDEBUG_CONFIG: ${XDEBUG_CONFIG:-client_host=172.17.0.1 client_port=9003 start_with_request=yes}
      TZ: ${TZ:-CET}
    volumes:
      - ./volumes/mediawiki:/var/www/mediawiki
  database:
    image: mariadb:${MARIADB_VERSION:-11.3.2}
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mediawiki}
      MYSQL_USER: ${MYSQL_USER:-mediawiki}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mediawiki}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      TZ: ${TZ:-CET}
    volumes:
      - ./volumes/database:/var/lib/mysql
  mailhog:
    image: blueimp/mailhog
    ports:
      - ${MAILHOG_PORT:-8025}:8025
